FROM php:8.3-apache
WORKDIR /var/www/html

RUN apt-get update && \
    apt-get install -y libmariadb-dev && \
    docker-php-ext-install mysqli pdo pdo_mysql && \
    # delete unused vulnerable pear
    pear uninstall pear