FROM php:8.3-apache
WORKDIR /var/www/html
RUN mkdir Articles
RUN apt-get update && apt-get install -y libmariadb-dev
RUN docker-php-ext-install mysqli pdo pdo_mysql
# delete unused vulnerable pear
RUN pear uninstall pear