#
name: Run and test the app

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['release']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate .env file
        run: | 
          cat <<EOF > .env
          DB_NAME = kiv_pia_test
          DB_USER = kiv_pia_root
          DB_PASS = kiv_pia_pass
          WEB_PORT = 8880
          PMA_PORT = 8881
          WSS_HOST = localhost # "publicly" reachable hostname of the websocket server -- accessed outside of container!
          EOF

      - name: Start the app
        run: ./prj_init.sh -t

      - name: install python dependencies
        run: pip3 install -r ./API_test/requirements.txt

      - name: Wait for the app to init
        uses: jakejarvis/wait-action@master
        with:
          time: '1m'

      - name: Prepare test files
        run: |
          cp API_test/test-article.pdf web/Articles/test1.pdf
          cp API_test/test-article.pdf web/Articles/test5.pdf
          cp API_test/test-article.pdf web/Articles/test7.pdf

      - name: Run tests
        run: cd API_test && pytest -v | tee result.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: API_test/result.txt