openapi: 3.0.0
info:
  title: 'Conference API'
  version: '0.1'
paths:
  '/api.php?service=get_auth_key':
    post:
      description: 'Create new authorization key for the user with the optionally specified expiration time and return it'
      operationId: 34e0d9e7027bdc42a94b2fbb73a2d3d4
      requestBody:
        content:
          application/json:
            schema:
              required:
                - login
                - pass
              properties:
                login:
                  description: 'Username or email'
                  type: string
                pass:
                  description: Password
                  type: string
                expiration:
                  description: 'Expiration time in seconds'
                  type: integer
                  default: 3600
              type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  key: { type: string }
                type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/api.php?service=get_user':
    get:
      description: 'Get user info: first name, last name, email, id. Admins also get rights and banned status.'
      operationId: 382ffa4dc9ee2972e957c1e258232d09
      parameters:
        -
          name: login
          in: query
          description: 'User login or email'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                required:
                  - fname
                  - lname
                  - email
                  - id
                properties:
                  fname: { description: 'First name', type: string }
                  lname: { description: 'Last name', type: string }
                  email: { description: Email, type: string }
                  id: { description: 'User ID', type: integer }
                  rights: { description: 'User rights', type: integer }
                  banned: { description: 'Is user banned', type: boolean }
                type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/api.php?service=get_user_articles':
    get:
      description: 'Get articles by user'
      operationId: cbc1ff07738ba8335e7198e95c0464e0
      parameters:
        -
          name: id
          in: query
          description: 'User ID'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/api.php?service=show_article':
    get:
      description: 'Get article contents article ID'
      operationId: 556ab51c15f1f3c868190de63f36ccc7
      parameters:
        -
          name: id
          in: query
          description: 'Article ID'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/api.php?service=get_articles':
    get:
      description: 'Get all ACCEPTED articles'
      operationId: c0807e8d1399e004e99f38aff59826f5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/api.php?service=ban_users':
    put:
      description: 'Ban users by logins or emails'
      operationId: e780d7d4726a19b2245e101ed99d534d
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/api.php?service=delete_article':
    delete:
      description: 'Delete user article by ID'
      operationId: 48c1861b7ddde7237441a70d6ec63ffa
      parameters:
        -
          name: id
          in: query
          description: 'Article ID'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/api.php?service=add_article':
    put:
      description: 'Add article information'
      operationId: 747869e17690d3af570e8d659162904d
      requestBody:
        content:
          application/json:
            schema:
              required:
                - title
                - key-words
                - descr
              properties:
                title:
                  type: string
                key-words:
                  type: string
                descr:
                  type: string
              type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/api.php?service=upload_article':
    post:
      description: 'Upload article file'
      operationId: 39103b6ca6e03ac02ccada0a07038547
      requestBody:
        content:
          application/pdf:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Article:
      properties:
        id:
          description: 'Article ID'
          type: integer
        title:
          description: 'Article title'
          type: string
        descr:
          description: Description
          type: string
        key-words:
          description: 'Key words'
          type: string
        approved:
          description: 'Approval status'
          type: string
          enum:
            - 'yes'
            - 'no'
            - pending
      type: object
    Error:
      required:
        - error
        - status
        - message
      properties:
        error:
          description: 'Error type'
          type: string
        status:
          description: 'HTTP status code'
          type: integer
        message:
          description: 'Error message'
          type: string
        redirect:
          description: 'API endpoint that may help resolve the error'
          type: string
      type: object
